language: ruby
rvm:
  - 2.1.3
env:
  BUNDLE_GEMFILE=$PWD/Gemfile
  RAILS_ENV=test
  SECRET_KEY_BASE="$(bundle exec rake secret)"
script: bundle exec rake db:create && bundle exec rake db:setup && bundle exec rake test
notifications:
    email:
        - brian.broll@gmail.com
